### ISSUE TITLE
Some small issues

### ISSUE THREAD

**Issue by warmstarter** [thenomain/Rhost-Support-Systems#1]
regexp should be regex, otherwise it gives a 'huh?' might be ok with aliases, but not everywhere.

The search() for ECO has a stray @create at the beginning.

I also get this message, but I have no idea what it's telling me or how to look into it/fix it: '<events installer> Well, I set a place for bboard events but it's not a real number so you might want to look into that.''

**Comment by thenomain** [comment]
> 'Well, I set a place for bboard events but it's not a real number so you might want to look into that.'

References https://github.com/thenomain/Rhost-Support-Systems/blob/main/Cobalt%20Events.txt#L94

In &d.bboard.events, put the number of the bboard you'll be using for posting of new events.

Will make this clearer.

**Comment by thenomain** [comment]
Should be fixed. Thanks!
