### ISSUE TITLE
moniker function

### ISSUE THREAD

**Issue by warmstarter** [thenomain/Rhost-Support-Systems#2]
I've got things setup, but you can see a broken moniker() function in plain +events:

======================[ Current PacificHorizon Events ]=======================
NUM          ST        Genre      Title           Date                     Sgnps
             moniker(                             Wed Dec 31 17:00 PST     3
             moniker(                             Wed Dec 31 17:00 PST     3
             moniker(                             Wed Dec 31 17:00 PST     3
====================================[ 3 ]=====================================

**Comment by thenomain** [comment]
Whups. When I get to it, or if you want to fix it in your own code: moniker -> cname

**Comment by thenomain** [comment]
Fixed.
