### ISSUE TITLE
help for functions

### ISSUE THREAD

**Issue by warmstarter** [thenomain/Rhost-Support-Systems#3]
0 - Theno Starter Code.txt

mentions to look at the more thorough help files for vcolumn and vtables, but they are not in the repo. It's possible there are other more thorough help files missing for functions, but I didn't check them all.

**Comment by thenomain** [comment]
Completely rewrote the formatting for the Starter Code, now in a folder with a "starter" document and a whole bunch of functions. Each with proper help files.

Thanks!
